# Generated by Django 5.1.6 on 2025-02-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
