# Generated by Django 5.1.6 on 2025-02-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_trade_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('INITIATED', 'Initiated'), ('FILLED', 'Filled'), ('CANCELED', 'Canceled')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['market', 'order_side', 'order_status', 'price'], name='core_order_market__7de2f2_idx'),
        ),
    ]
