# Generated by Django 5.1.6 on 2025-02-12 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='core_order_market__7de2f2_idx',
        ),
    ]
