# Generated by Django 5.1.6 on 2025-02-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_order_core_order_market__7de2f2_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['market', 'order_side', 'order_status'], name='core_order_market__38dc39_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['price'], name='core_order_price_2551cd_idx'),
        ),
    ]
