# Generated by Django 5.1.6 on 2025-02-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_core_order_market__38dc39_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='core_order_market__38dc39_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='core_order_price_2551cd_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_side',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('INITIATED', 'Initiated'), ('FILLED', 'Filled'), ('PARTIALLY_FILLED', 'Partially Filled'), ('CANCELED', 'Canceled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('LIMIT', 'Limit'), ('MARKET', 'Market')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['market', 'order_side', 'order_status', 'price'], name='core_order_market__7de2f2_idx'),
        ),
    ]
