# Generated by Django 5.1.6 on 2025-02-16 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_order_core_order_market__38dc39_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='core_order_market__7de2f2_idx',
        ),
    ]
